<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	  <IsAotCompatible>true</IsAotCompatible>
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroRepository.Core\MicroRepository.Core.csproj" />
  </ItemGroup>

</Project>
