using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MicroRepository.Repository.Attributes
{
    public class PrimaryKeyAttribute : Attribute
    {
        public PrimaryKeyAttribute(bool isAutoGenerated)
        {
            IsAutoGenerated = isAutoGenerated;
        }
        public bool IsAutoGenerated { get; private set; }
        
    }
}
