

using System.Text;
using System;
using System.Text.RegularExpressions;
using MicroRepository.Repository.Enums;
using MicroRepository.Repository;

namespace MicroRepository.Templates
{
    internal abstract class SqlTemplate
    {
        // Propriétés virtuelles au lieu de constantes
        internal virtual string Select => "SELECT /**distinct**/ {0} FROM {1} /**innerjoin**/ /**leftjoin**/ /**rightjoin**/ /**where**/ /**orderby**/ /**take**/ /**skip**/";
        internal virtual string Update => "UPDATE {0} SET {1} /**where**/";
        internal virtual string Insert => "INSERT INTO {0} ({1}) VALUES ({2})";
        internal virtual string Delete => "DELETE FROM {0} /**where**/";
        internal virtual string AutoGenerated => "";
        internal virtual string Separator => ", ";
        internal virtual string QuoteChar => "{0}";
        internal virtual string Take => "";
        internal virtual string Skip => "";

        internal virtual CaseFormat CaseFormat => CaseFormat.Default;

        internal string EnquoteTableName(string tableName)
        {
            return DbSettings.EnquoteTableNames ? Enquote(tableName) : tableName;
        }

        internal string EnquoteColumnName(string columnName)
        {
            return DbSettings.EnquoteColumnNames ? Enquote(columnName) : columnName;
        }
        private string Enquote(string? column)
        {
            ArgumentNullException.ThrowIfNull(column, nameof(column));
            return string.Format(QuoteChar, column);

        }

    }

    internal class MsSqlTemplate : SqlTemplate
    {
        internal override string AutoGenerated => ";SELECT SCOPE_IDENTITY();";
        internal override string QuoteChar => "[{0}]";
        internal override string Take => "OFFSET {0} ROWS";
        internal override string Skip => "FETCH NEXT {0} ROWS ONLY";
    }

    internal class MySqlTemplate : SqlTemplate
    {
        internal override string AutoGenerated => ";SELECT LAST_INSERT_ID();";
        internal override string QuoteChar => "`{0}`";
        internal override string Take => "LIMIT";
        internal override string Skip => "OFFSET";
    }

    internal class SQLiteTemplate : SqlTemplate
    {
        internal override string AutoGenerated => ";SELECT last_insert_rowid();";
        internal override string QuoteChar => "`{0}`";
        internal override string Take => "LIMIT";
        internal override string Skip => "OFFSET";
    }

    internal class PostgreSqlTemplate : SqlTemplate
    {        
        internal override string QuoteChar => "\"{0}\"";
        internal override string Take => "LIMIT";
        internal override string Skip => "OFFSET";
        internal override string AutoGenerated => " RETURNING Id;";

    }
}

