using MicroRepository.Core.Schema;
using MicroRepository.Repository;
using MicroRepository.Repository.Attributes;
using System;
using System.Reflection;

namespace MicroRepository.Schema
{
    public class ColumnDescriptor
    {
        public string Name { get { return Property.Name; } }
        public Type Type { get { return Property.PropertyType; } }

        public PropertyInfo Property { get { return _compiledPropertyAccessor.Property; } }

        public string DbName { get; private set; }
        public string FullDbName { get; private set; }
        public bool IsPrimaryKey { get; private set; }
        public bool IsAutoId { get; private set; }

        internal CompiledPropertyAccessor<object> _compiledPropertyAccessor;

        string _selectString = string.Empty;
        internal string SelectString
        {
            get
            {
                if (string.IsNullOrEmpty(_selectString))
                {
                    if (Name != DbName)
                        _selectString = $"{FullDbName} AS {DbSettings.Template.EnquoteColumnName(Name)}";
                    else
                        _selectString = $"{FullDbName}";
                }
                return _selectString;
            }
        }

        string _updateString = string.Empty;
        internal string UpdateString
        {
            get
            {
                if (string.IsNullOrEmpty(_updateString))
                    _updateString = $"{DbName} = @{Name}";

                return _updateString;
            }
        }

        internal void Copy<T>(T entity, T original) where T : class
        {
            _compiledPropertyAccessor.Copy(entity, original);
        }


        //public bool IsRelation { get; private set; }

        public ColumnDescriptor(CompiledPropertyAccessor<object> compiledProperty, string tableName)
        {
            _compiledPropertyAccessor = compiledProperty;

            // Check for [Map] attribute
            MapAttribute? mapAttribute = _compiledPropertyAccessor.Property.GetCustomAttribute<MapAttribute>();
            if (mapAttribute != null && mapAttribute.Name != Name)
                DbName = DbSettings.Template.EnquoteColumnName(mapAttribute.Name);
            else
                DbName = DbSettings.Template.EnquoteColumnName(Name);
            

            
            FullDbName = $"{tableName}.{DbName}";
            PrimaryKeyAttribute? isKey = _compiledPropertyAccessor.Property.GetCustomAttribute<PrimaryKeyAttribute>();

            if (isKey!=null)
            {
                IsPrimaryKey = true;
                IsAutoId = isKey.IsAutoGenerated;
            }
            
            //var isRelation = keyProperty.GetCustomAttribute<RelationAttribute>();
            //this.IsRelation = isRelation != null;
        }

        internal object Get<T>(T entity) where T : class
        {
            return _compiledPropertyAccessor.Get(entity);
        }
    }
}
