using MicroRepository.Core.Caching;
using MicroRepository.Repository.Attributes;
using MicroRepository.Repository;
using MicroRepository.Templates;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace MicroRepository.Schema
{
    /// <summary>
    /// Defines table metadata for an entity type.
    /// </summary>
    public class TableDescriptor
    {
        public string Name { get; private set; } = string.Empty;
        public string DBName { get; private set; } = string.Empty;

        public string Alias { get; private set; } = string.Empty;
        public bool HasAutoId { get; private set; }
        public Dictionary<string, ColumnDescriptor> Members { get; private set; }
        public string SelectTemplate { get; private set; } = string.Empty;
        public string CountTemplate { get; private set; } = string.Empty;
        public string DeleteTemplate { get; private set; } = string.Empty;
        public string InsertTemplate { get; private set; } = string.Empty;
        public string UpdateTemplate { get; private set; } = string.Empty;

        /// <summary>
        /// Initializes a new instance of the <see cref="TableDescriptor"/> class.
        /// </summary>
        /// <param name="targetType">The type representing the entity.</param>
        /// <param name="name">Optional custom table name.</param>
        public TableDescriptor(Type targetType)
        {
            ArgumentNullException.ThrowIfNull(targetType, nameof(targetType));

            
            if (DbSettings.Template == null)
            {
                throw new InvalidOperationException("Repository template is not initialized.");
            }

            InitializeTableName(targetType);
            InitializeColumnDescriptor(targetType);
            InitializeTemplates(DbSettings.Template);
        }

        /// <summary>
        /// Initializes the table name and view-related metadata.
        /// </summary>
        private void InitializeTableName(Type targetType)
        {
            TypeInfo targetTypeInfo = targetType.GetTypeInfo();
            Name = targetType.Name;


            // Check for [Map] attribute
            var mapAttribute = targetTypeInfo.GetCustomAttribute<MapAttribute>();


            if (mapAttribute != null && mapAttribute.Name != Name)
            {
                DBName = $"{DbSettings.Template.EnquoteTableName(mapAttribute.Name)}";                
            }
            else
            {
                DBName = DbSettings.Template.EnquoteTableName(Name);
            }
            Alias = $"_{Name.ToLower()}";

        }

        /// <summary>
        /// Initializes the properties (members) of the entity, including metadata for mapping.
        /// </summary>
        private void InitializeColumnDescriptor(Type targetType)
        {
            var cachedProperties = ReflectionCache.GetProperties(targetType);

            Members = cachedProperties.Values
                .Where(prop => !prop.Property.IsDefined(typeof(NotMappedAttribute)))
                .Select(prop => new ColumnDescriptor(prop, Alias))
                .ToDictionary(accessor => accessor.Name);

            HasAutoId = Members.Values.Any(member => member.IsAutoId);
        }

        /// <summary>
        /// Initializes SQL templates for various CRUD operations.
        /// </summary>
        private void InitializeTemplates(SqlTemplate template)
        {
            // SELECT template
            //SelectTemplate = Members.Values.Any(member => member.IsAutoId)
            //    ? string.Format(template.Select, template.Enquote(Name) + ".*", DBName)
            //    : string.Format(template.Select, string.Join(", ", Members.Values.Select(member => member.SelectString)), DBName);
            SelectTemplate = string.Format(template.Select, string.Join(", ", Members.Values.Select(member => member.SelectString)), $"{DBName} AS {Alias}");

            // COUNT template
            CountTemplate = string.Format(template.Select, "COUNT(*)", DBName);

            // DELETE template
            DeleteTemplate = string.Format(template.Delete, DBName);

            // UPDATE template
            UpdateTemplate = string.Format(template.Update,
                DBName,
                string.Join(", ", Members.Values.Where(member => !member.IsPrimaryKey).Select(member => member.UpdateString)));

            // INSERT template
            var insertTemplate = template.Insert;
            if (HasAutoId)
            {
                insertTemplate += template.AutoGenerated; // Append identity retrieval (e.g., SCOPE_IDENTITY)
            }

            var dbColumns = Members.Values
                .Where(member => !member.IsAutoId)
                .Select(member => member.DbName);

            var objectColumns = Members.Values
                .Where(member => !member.IsAutoId)
                .Select(member => $"@{member.Name}");

            InsertTemplate = string.Format(insertTemplate,
                DBName,
                string.Join(", ", dbColumns),
                string.Join(", ", objectColumns));
        }
    }
}